### ISSUE TITLE
create pypi package

### ISSUE THREAD

**Issue by fhamborg** [fhamborg/Giveme5W1H#17]

**Comment by fhamborg** [comment]
https://mail.google.com/mail/u/0/#inbox/16316ada31dd478f

**Comment by fhamborg** [comment]
done

**Comment by fhamborg** [comment]
**info by Benedikt**
Gem. Doku(https://packaging.python.org/tutorials/packaging-projects/) war die Projekt-Struktur falsch. Daher wurde jeder Unterordner als eigenes Paket installiert; kannst du es mal testen(1.0.5) ?

PyCharm wollte die Dateien nicht kopieren. Daher gibts jetzt neue Projekt-Dateien. Was noch fehlt ist 'Giveme5W1H.iml' in Root. Ich habe gesehen, dass du diese angepasst hast. Mir ist nicht ganz klar ob wir die wieder brauchen....

Runtime-resources: Wer es nur via PIP/Console starten will, muss lediglich CoreNLP via default URL gestartet haben.
Für Runtime-resources ist einiges implementiert, hat sich aber alles als "unnötig" herausgestellt:
CoreNLP (nur für startup scripte)
Heideltime (Enhancer, nicht wirklich genutzt da wir schlussendlich SUTime benutzt haben)
TreeTagger (Braucht nur Heideltime)
AIDA (Theoretische lokale Installation, GIT ist inzwischen offline, daher nicht wirklich nützlich)
=> Wer giveme5w1h benutzt und nicht entwickelt braucht diesen Ordner eigendlich nicht
Server.py kann nicht CoreNLP starten & weil das Starten sehr lange dauert, will man CoreNLP eigentlich nie herunterfahren/neustarten. Ich denke dies ist der Hauptgrund, warum noch keiner ein PIP Paket geschrieben hat, welches CoreNLP downloaded & startet.

Ich glaube diese TODOs müssen gemacht werden. Damit es via PIP wirklich gut funktioniert.
CoreNLP Server in ein eigenes PIP; mit download, start, stop 
Giveme5W1H sollte alle Pfade z.B. via root.py bauen
root.py sollte bei PIP installation z.b auf  ~/Giveme5w1h/' umstellen
Giveme5W1H sollte eine Config gem. root.py(config.json) suchen und mit Configuration.py mergen, sofern installation via PIP.
Config sollten den Enhancer import an/ausschalten können
Cache sollte ggf. in ein eigenes PIP (NewsClsuter benutzt gleiche Implementierung...)
Try Catch beim laden einer Cache-Datei
Cache Pfad gem. root.py
Tricky ist eigentlich nur den CoreNLP Server bereitstellen & Windows support...

btw. Ich habe nichts gefunden, dass Spacy mit CoreNLP vergleicht. Aber Spacy wäre echt ne super alternative zu CoreNLP, weil alles via PIP verfügbar ist. Aber mir klar, dass CoreNLP aktuell nicht einfach ausgetauscht werden kann ^^.

**Comment by nitinthewiz** [comment]
@fhamborg may I ask you to clarify something here? Why have you said that CoreNLP cannot be exchanged at the moment? spaCy does seem to be a very lucrative alternative to me for this project, specially since there's no server to run, everything installs through pip, as you've mentioned. Just looking for some clarification...
