### ISSUE TITLE
Other languages compatibility?

### ISSUE THREAD

**Issue by guiscaranse** [fhamborg/Giveme5W1H#20]
I want to know what is need to adapt it to another language? (e.g Brazilian Portuguese)
Or is it possible to integrate with [Polyglot](https://github.com/aboSamoor/polyglot) which already implement a lot of NLTK compatible languages?

**Comment by fhamborg** [comment]
Definitely, you can have a look in the papers mentioned in the Readme.MD for the specifics, which you would need to adapt the extraction and scoring process to another language. Likewise, this could be integrated with another library, such as Polyglot.

**Comment by guiscaranse** [comment]
Hey @fhamborg I took a look at the papers. Replacing the original CoreNLP with another one, trained strictly for another language is enough? Since the classifiers use the NER POS tag which in theory should remain the same for another language. Or we would need to remake the datasets, and other stuff to achieve the language recognition?

**Comment by fhamborg** [comment]
I'm not familiar with the characteristics of neither the Brazilian language nor Brazilian news articles, but generally I'd recommend to change the models / language used in Stanford to Brazilian, first, and then see if further adaptions are required. These adaptions may include changes necessary to the extraction methods for the questions, and to the scoring methods.
