### ISSUE TITLE
ModuleNotFoundError: No module named 'extractor'

### ISSUE THREAD

**Issue by chaos87** [fhamborg/Giveme5W1H#21]
Hi,

First thanks for this very promising tool.

I followed the step by step installation guide and could get all the dependencies but when I run this snippet of code 
`from extractor.document import Document
from extractor.extractor import FiveWExtractor

extractor = MasterExtractor()
doc = Document(title, lead, text, date_publish)
doc = extractor.parse(doc)`

It gives me the `ModuleNotFoundError: No module named 'extractor'`

I have python 3.6.2 and installed in Docker container with Ubuntu 16.04. I ran 
$ pip3 install giveme5w1h
$ giveme5w1h-corenlp install
and install went OK.

Thanks for your help!

**Comment by fhamborg** [comment]
fixed 2651d342ca8e64f62130d520445a36fa95805d2e

**Comment by fhamborg** [comment]
Thanks for the hint. I've updated the readme.md, containing a fixed description, e.g., you'll need to use `from Giveme5W1H.extractor.document import Document` instead of`from extractor.document import Document`

**Comment by chaos87** [comment]
Thanks for the prompt reply!
Should we use FiveWExtractor instead of MasterExtractor?
