### ISSUE TITLE
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

### ISSUE THREAD

**Issue by chaos87** [fhamborg/Giveme5W1H#22]
Hi,

I tried getting the 5W and the How from this article https://digiday.com/media/guardian-launches-nonprofit-fund-journalism/?utm_medium=email&utm_campaign=digidaydis&utm_source=publishing&utm_content=170828

For that I used: 
1) news-please, to extract article title/text/date-publish (Thanks by the way, this tool is just awesome!)
2) I started the corenlp java on a remote server and configured the preprocessor like this:
`
from Giveme5W1H.extractor.preprocessors.preprocessor_core_nlp import Preprocessor
preprocessor = Preprocessor('http://XX.XXX.XX.XXX:80')
`

and tried accessing it with this bit of code
`
extractor = FiveWExtractor(preprocessor=preprocessor)
doc = Document(title=article.title, text=article.text, date=article.date_publish.strftime('%Y-%m-%d'))
doc = extractor.parse(doc)
print("done")
`
Unfortunately it yields the same error (after roughly 1 min).
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
I attached the logs for the extractor.parse call
[logs.txt](https://github.com/fhamborg/Giveme5W1H/files/2176906/logs.txt)

Could you please help figure out how to make this work? Thanks!

**Comment by fhamborg** [comment]
see https://github.com/fhamborg/news-please/issues/66
