### ISSUE TITLE
Error installing corenlp

### ISSUE THREAD

**Issue by gnageeb** [fhamborg/Giveme5W1H#23]
Hello!
Thanks for making this project available, however I cannot successfully install the RESTful API for it. I run:
$ pip3 install giveme5w1h
$ giveme5w1h-corenlp install
The former installs successfully while the latter issues the following error:
 giveme5w1h-corenlp: command not found
would you please advise? Thanks in advance

**Comment by fhamborg** [comment]
Which OS are you using? I guess this issue is related to your PATH variable not being setup properly by PIP. Please also post the full PIP install log.

**Comment by gnageeb** [comment]
Ubuntu 18, and the log is attached

[installation_log.log](https://github.com/fhamborg/Giveme5W1H/files/2227486/installation_log.log)

**Comment by fhamborg** [comment]
I dont see any issue in the log, so my guess would be that the PATH variable is not setup properly by PIP. Does `giveme5w1h-rest` work?

**Comment by gnageeb** [comment]
giveme5w1h-rest isn't working too, I am assuming that these commands should be installed in site-packages right? cause I checked and they are not there either.

**Comment by gnageeb** [comment]
Tried installing using sudo -H and it is worked! thanks very much! however there is an internal server error that occurs when running giveme5w1h-rest, you might want to have a look at it. Thanks again for you cooperation. Much appreciated!

**Comment by fhamborg** [comment]
abff72cbc8a80d1935002d8f5471c5805f5e6ea1
