### ISSUE TITLE
Consider other NLP tools

### ISSUE THREAD

**Issue by physikerwelt** [fhamborg/Giveme5W1H#24]
@fhamborg  you might be interested in https://github.com/zalandoresearch/flair developed by my former colleague @alanakbik
From a first glance, I get the impression that this library does not require starting a [java rest server](https://github.com/fhamborg/Giveme5W1H#why-do-i-need-to-manually-start-the-stanford-corenlp-server) and is written in python. The performance results seem promising.

**Comment by fhamborg** [comment]
Looks pretty promising, thanks for the hint!
