### ISSUE TITLE
About the parameter in the "environment extraction

### ISSUE THREAD

**Issue by lastshogun** [fhamborg/Giveme5W1H#28]
Thanks for the answer, and I'm wondering could you show me where can I find the specific definition of the three parameters" entailment, distance_from_publisher_date, accurate" in environment initialization program? Just in order to justify them properly.

**Comment by fhamborg** [comment]
Which commit level are you using?

**Comment by lastshogun** [comment]
I'm using the newest version currently.

**Comment by fhamborg** [comment]
As I said in the other issue that you opened, if you want to reconstruct the version from the publication, you cannot use the latest version but need to use the commits view to select the one with the same publication date. Hope this helps :-)
