### ISSUE TITLE
"newsCluster" item in json files in Giveme5W1H/examples/datasets/40er/data

### ISSUE THREAD

**Issue by zhnlp** [fhamborg/Giveme5W1H#46]
Thanks for your great work!

Recently, I'm working on a project to cluster news by the event. The item named "newCluster" in your dataset looks good for this purpose. 

Is it extracted automatically? If so, would you mind provide us more details about how to get it?

```json
"newsCluster": {
    "CategoryId": 1,
    "Category": "world",
    "TopicId": 2,
    "Topic": "legancy",
    "EventId": 49,
    "Event": "las_vegas_shooting",
    "Url": "http://usa.chinadaily.com.cn/world/2017-10/03/content_32788252.htm"
  }
```

**Comment by fhamborg** [comment]
Thank you! Re your question, I'm sorry, but unfortunately nothing much: I do recall that we added this data for a news clustering project, but that's long ago.
